version: '4'

services:
  async:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0
    ports:
     - 8000:8000	
    volumes:
      - .:/app
    extra_hosts:
     - "host.docker.internal:host-gateway"
  

 
